//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Архивариус
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive_work
    {
        public int ID_Archive { get; set; }
        public int Сase_index { get; set; }
        public System.DateTime YearCreate { get; set; }
        public System.DateTime YearFinish { get; set; }
        public string Title { get; set; }
        public string Note { get; set; }
        public int Number_of_cases { get; set; }
        public int Storage_article_ID { get; set; }
    
        public virtual Storage_article Storage_article { get; set; }
    }
}
