//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Архивариус
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive_work
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Archive_work()
        {
            this.Issuance = new HashSet<Issuance>();
        }
    
        public int ID_Archive { get; set; }
        public int Сase_index { get; set; }
        public System.DateTime YearCreate { get; set; }
        public System.DateTime YearFinish { get; set; }
        public string Title { get; set; }
        public string Note { get; set; }
        public int Number_of_cases { get; set; }
        public int Storage_article_ID { get; set; }
    
        public virtual Storage_article Storage_article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issuance> Issuance { get; set; }
    }
}
