//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Архивариус
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive_of_electronic_documents
    {
        public int ID_Archive_of_electronic_documents { get; set; }
        public string Сase_index { get; set; }
        public string Title { get; set; }
        public string Way { get; set; }
        public int Storage_article_ID { get; set; }
    
        public virtual Storage_article Storage_article { get; set; }
    }
}
