//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Архивариус
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorized_user_role
    {
        public int ID_Authorized_user_role { get; set; }
        public int Reg_ID { get; set; }
        public System.DateTime Date_authorized_user_role { get; set; }
    
        public virtual Reg Reg { get; set; }
    }
}
