//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Архивариус
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage_article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Storage_article()
        {
            this.Archive_of_electronic_documents = new HashSet<Archive_of_electronic_documents>();
            this.Archive_work = new HashSet<Archive_work>();
        }
    
        public int ID_Storage_article { get; set; }
        public string Storage_article1 { get; set; }
        public string Shelf_life_by_article { get; set; }
        public string Note_on_storage_article { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Archive_of_electronic_documents> Archive_of_electronic_documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Archive_work> Archive_work { get; set; }
    }
}
